### ISSUE TITLE
Can no longer run from a zc.buildout

### ISSUE THREAD

**Issue by nutjob4life** [Jarn/jarn.mkrelease#10]
My ~/bin directory is a zc.buildout which includes jarn.mkrelease. With the commit 6fb4ae2e643752d9b0b0c22beabfc06c822ab383 to setuptools.py, mkrelease now tries to run `from jarn.mkrelease import setup; setup.run(%(args)r, ff=%(ff)r)'`; however since jarn.mkrelease is sequestered in the buildout, Python fails with:

    running egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named jarn.mkrelease
    egg_info failed

Workaround is to install jarn.mkrelease in the global Python, but I'd rather not.

**Comment by stefanholek** [comment]
Sorry I missed this. I guess that's what you get from disabling notifications. :-(

Fixed now in 4.3. Thanks for the report.
